#!/usr/bin/env ruby
# Migrate from DB version one to version two
# Inside rails root: rails runner -e production script/migrate_two

PASSWORD = ''

gameroom_old = Mysql2::Client.new(:host => 'localhost', :username => 'root', :password => PASSWORD, :database => 'gameroom_old')

Till.destroy_all
tills = gameroom_old.query("SELECT * FROM tills")
tills.each do |till|
  till = Till.create({
    :title => till["title"],
    :description => till["description"],
    :minimum_balance => till["minimum_balance"],
    :minimum_transfer => till["minimum_transfer"],
    :retainable => till["retainable"],
    :active => till["active"]
  })
end

Person.destroy_all
User.destroy_all
Customer.destroy_all
Phone.destroy_all
Address.destroy_all
people = gameroom_old.query("SELECT * FROM people")
people.each do |person|
  new_person = Person.create({
    :first_name => person["first_name"],
    :middle_name => person["middle_name"],
    :last_name => person["last_name"],
    :date_of_birth => person["date_of_birth"]
  })
  addresses = gameroom_old.query("SELECT * FROM addresses WHERE person_id = #{person["id"]}")
  addresses.each do |address|
    Address.create({
      :person_id => new_person.id,
      :first_line => address["first_line"],
      :second_line => address["second_line"],
      :city => address["city"],
      :state => address["state"],
      :country => address["country"],
      :zip => address["zip"]
    })
  end
  phones = gameroom_old.query("SELECT * FROM phones WHERE person_id = #{person["id"]}")
  phones.each do |phone|
    Phone.create({
      :person_id => new_person.id,
      :title => phone["title"],
      :number => phone["number"]
    })
  end
  if person["user_id"] != nil
    users = gameroom_old.query("SELECT * FROM users WHERE id = #{person["user_id"]}")
    users.each do |user|
      User.create({
        :person_id => new_person.id,
        :rate => 0,
        :pin => '0000',
        :login => user["login"],
        :email => user["email"],
        :password => 'password',
        :password_confirmation => 'password',
        :administrator => user["administrator"],
        :active => user["active"]
      })
    end
  end
  if person["customer_id"] != nil
    customers = gameroom_old.query("SELECT * FROM customers WHERE id = #{person["customer_id"]}")
    customers.each do |customer|
      Customer.create({
        :person_id => new_person.id,
        :credit => customer["credit"],
        :drivers_license_number => customer["drivers_license_number"],
        :drivers_license_state => customer["drivers_license_state"],
        :notes => customer["notes"],
        :active => customer["active"]
      })
    end
  end
end

Item.destroy_all
Property.destroy_all
items = gameroom_old.query("SELECT * FROM items")
items.each do |item|
  if item["sku"] != nil
    credit = 0
    cash = 0
    tags = []
    properties = gameroom_old.query("SELECT * FROM properties WHERE item_id = #{item["id"]}")
    properties.each do |property|
      if property["key"] == 'credit_price'
        credit = property["value"]
      elsif property["key"] == 'cash_price'
        cash = property["value"]
      elsif property["key"] == 'type'
        tags.push(property["value"].downcase.capitalize)
      else
        tags.push(property["value"])
      end
    end
    item = Item.create({
      :title => item["title"],
      :description => item["description"],
      :tags => tags.join(','),
      :sku => item["sku"],
      :price => item["price"],
      :credit => credit,
      :cash => cash,
      :taxable => item["taxable"],
      :discountable => true,
      :locked => item["locked"],
      :active => item["active"]
    })
  end
end